### ISSUE TITLE
Issue edit height bug

### ISSUE THREAD

**Issue by pmdarrow** [mdo/github-wide#20]
When I edit an issue with this user style enabled, extra whitespace appears below the form controls. I'm using the latest Chrome. Here's what it looks like:

![edit issue height bug](https://cloud.githubusercontent.com/assets/586800/8355066/5ce0f5ac-1b23-11e5-8824-4150a3cef72c.gif)

**Comment by tophf** [comment]
```css
.comment-body:after {
	clear: none
}
```

**Comment by mdo** [comment]
Ah, related to a bugfix we just shipped. Sorry about that :grin:.

@tophf If that works, want to open a pull request? :D

**Comment by tophf** [comment]
Nah, I haven't tested for possible ramifications.

**Comment by mdo** [comment]
`.comment-body` only appears on issues, pull requests, and commits.

**Comment by tophf** [comment]
As I hate `float` and love `flex` here's the fix I use locally:

```css
#discussion_bucket {display:flex}
.discussion-timeline {float:none; order:1; margin-right:20px!important}
.discussion-sidebar {float:none; order:2}
```
