### ISSUE TITLE
Fix notifications, create and profile icons

### ISSUE THREAD

**Issue by adius** [mdo/github-wide#31]
The notifications, create and profile icons in the navigation bar don't move inwards when windows is smaller,

**Comment by adius** [comment]
By the way, I fixed it for me with:

```css
.header {
	min-width: inherit;
}

.pagehead {
	min-width: inherit;
}
```
