### ISSUE TITLE
Slight change for issues view

### ISSUE THREAD

**Issue by nickcampbell18** [mdo/github-wide#66]
GitHub seem to have released a small change yesterday which uses columns on the PR page. These two CSS declarations are now breaking the display:

```css
/* Issues/PRs */
.discussion-sidebar {
  width: 280px !important;
}
.discussion-timeline {
  width: calc(100% - 300px) !important;
}
```

I've found just removing them seems to revert to the old behaviour :+1:

### Before

<img width="1918" alt="Before screenshot - columns are wrong" src="https://user-images.githubusercontent.com/661795/61937685-ee48cf80-af7e-11e9-892c-9c75319ef602.png">

### After

<img width="1917" alt="After screenshot (overrides removed)" src="https://user-images.githubusercontent.com/661795/61937723-028ccc80-af7f-11e9-8570-1db933b45fa2.png">
